name: Go CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install SSH client
    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y ssh

    # Deploy to GCP VM
    - name: Deploy to GCP VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          GODEBUG: netdns=go
          GODEBUG_NETDNS_RESOLVCONF: /etc/resolv.conf
          GODEBUG_NETDNS_RESOLV: 8.8.8.8  # Use Google DNS server
        script: |
          scp -i /home/amandeep/.ssh/id_rsa ${{ github.workspace }}/myapp ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/amandeep/Deployment
          ssh -i /home/amandeep/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "sudo systemctl restart myapp.service"
